language: node_js
node_js:
  - "0.10.30"

branches:
  only:
    - master

addons:
  postgresql: "9.3"

before_install:
  # Position ourselves to start the test in "script" phase
  - cd ~/build/CUL-DigitalServices/grasshopper

  # Configure postgres
  - psql -c 'create database grasshoppertest;' -U postgres
  - printf "\n\nconfig.db.username = 'postgres';" >> config.js

script:
  - grunt test-coverage-coveralls

notifications:
  email:
    - bp323@cam.ac.uk
    - md623@cam.ac.uk
  irc:
    channels:
      - "irc.freenode.org#ucam-ds"
    skip_join: true
